# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiling', '0003_habitsantecedents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('seguimiento', models.IntegerField(default=1)),
                ('colesterolldl', models.FloatField(default=0)),
                ('colesterolhdl', models.FloatField(default=0)),
                ('trigliceridos', models.FloatField(default=0)),
                ('pas', models.FloatField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntajeCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(default=1)),
                ('nombre', models.CharField(default='Diego', max_length=50)),
                ('minmala', models.IntegerField(default=1)),
                ('maxmala', models.IntegerField(default=1)),
                ('minbuena', models.IntegerField(default=1)),
                ('maxbuena', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestAsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField(default=0)),
                ('p2', models.IntegerField(default=0)),
                ('p3', models.IntegerField(default=0)),
                ('p4', models.IntegerField(default=0)),
                ('p5', models.IntegerField(default=0)),
                ('p6', models.IntegerField(default=0)),
                ('p7', models.IntegerField(default=0)),
                ('p8', models.IntegerField(default=0)),
                ('p9', models.IntegerField(default=0)),
                ('p10', models.IntegerField(default=0)),
                ('p11', models.IntegerField(default=0)),
                ('p12', models.IntegerField(default=0)),
                ('p13', models.IntegerField(default=0)),
                ('p14', models.IntegerField(default=0)),
                ('p15', models.IntegerField(default=0)),
                ('p16', models.IntegerField(default=0)),
                ('p17', models.IntegerField(default=0)),
                ('p18', models.IntegerField(default=0)),
                ('p19', models.IntegerField(default=0)),
                ('p20', models.IntegerField(default=0)),
                ('p21', models.IntegerField(default=0)),
                ('p22', models.IntegerField(default=0)),
                ('p23', models.IntegerField(default=0)),
                ('p24', models.IntegerField(default=0)),
                ('resultado', models.IntegerField(default=0)),
                ('nombre', models.CharField(default='Baja', max_length=10)),
                ('fecha', models.DateField(auto_now=True)),
                ('seguimiento', models.IntegerField(default=0)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='observaciones',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.PuntajeCategoria'),
        ),
    ]
