# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20170923_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.Paciente'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(blank=True, null=True, to='medical.Pregunta'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.TipoExamen'),
        ),
        migrations.AlterField(
            model_name='observaciones',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.PuntajeCategoria'),
        ),
    ]
