# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_auto_20170923_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='medical.Pregunta'),
        ),
    ]
