# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_auto_20170923_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medical.Pregunta')),
            ],
        ),
        migrations.RemoveField(
            model_name='examen',
            name='preguntas',
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='preguntas',
            field=models.ManyToManyField(blank=True, to='medical.Pregunta'),
        ),
        migrations.AddField(
            model_name='examen',
            name='respuestas',
            field=models.ManyToManyField(blank=True, to='medical.Respuesta'),
        ),
    ]
