# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20170924_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.CategoriaPregunta'),
        ),
    ]
