# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_auto_20170924_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='seguimiento',
            field=models.IntegerField(default=0),
        ),
    ]
