# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_examen_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='profiling.Paciente'),
        ),
    ]
