# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_auto_20171011_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='slug',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
