# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_auto_20171011_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntajecategoria',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.PuntajeCategoria'),
        ),
    ]
