# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0020_auto_20171011_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciones',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='medical.PuntajeCategoria'),
        ),
    ]
