# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paciente', models.CharField(default='123456789', max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('telefono', models.CharField(max_length=30)),
                ('estado_civil', models.CharField(choices=[('Uni\xf3n Libre', 'Uni\xf3n Libre'), ('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], max_length=35)),
                ('estrato', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='RegimenSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='regimen_salud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiling.RegimenSalud'),
        ),
    ]
