# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='Diego', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='primer_apellido',
            field=models.CharField(default='Angulo', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='segundo_apellido',
            field=models.CharField(default='Perez', max_length=50),
        ),
    ]
