# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_auto_20170912_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitsAntecedents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabaquismo', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('iam', models.BooleanField(default=False)),
                ('seguimiento', models.IntegerField(default=1)),
                ('fecha', models.DateField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.Paciente')),
            ],
        ),
    ]
