# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0003_habitsantecedents'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
