# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0005_auto_20171009_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cod_paciente',
            field=models.CharField(default='123456789', max_length=50, unique=True),
        ),
    ]
