# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0006_auto_20171009_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitsantecedents',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='profiling.Paciente'),
        ),
    ]
