# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0007_auto_20171009_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
